### ISSUE TITLE
obfuscated keys

### ISSUE THREAD

**Issue by jerryyhom** [pokemongo-dev-contrib/pokemongo-game-master#123]
In the JSON formatted Game Master, many keys are obfuscated as a fixed length string, such as below.  What happened?  The raw Game Master is really obfuscated?

```
    "templateId": "AR_TELEMETRY_SETTINGS",
    "data": {
      "lakkjnlnilh": "AR_TELEMETRY_SETTINGS",
      "mckdimdpkdk": {
        "ffhkfdimdec": true,
        "gmpciheaacc": 10000,
        "khnjkldmaia": true,
        "nioolkbcikm": 10000,
        "ebnjkmmdmal": 0.5
      }
    }
  }, {
    "templateId": "AVATAR_GROUP_ORDER_SETTINGS",
    "data": {
      "lakkjnlnilh": "AVATAR_GROUP_ORDER_SETTINGS",
      "lamppehpdll": {
        "ningpplnbao": [{
          "cmajimdklmc": "group_uniqlo",
          "jhpcchioiam": 1
        }]
      }
    }
```

**Comment by Furtif** [comment]
not the game master but the protos yes

**Comment by jerryyhom** [comment]
Can the keys be un-obfuscated?  There seems to be a unique, one-to-one mapping with the original keys.  How are others handling it?

**Comment by Furtif** [comment]
should translate json always easier to translate repeated keys in json than translate protos all 💁🏻‍♂️🤷🏻‍♂️

**Comment by jerryyhom** [comment]
On a separate note, in the section for pokemon types, the attackScalar arrays are missing.  Can you please check if they are somehow silently dropped?  Thanks.

**Comment by Furtif** [comment]
possible has a lot that changed in 185 even in 183 the last version without ofuscated was the 181 surely it all has to be seen better but a good start at the beginning ie get used to it all

**Comment by jerryyhom** [comment]
Sorry, I meant, in the decoding process from protobuf to json, maybe the attackScalar arrays are thrown away?  I can see the values in older versions.  For example, in 1595879989869 below, the pokemon types have only two pieces of data.  In the latest version, attackScalar is missing completely.  Can you confirm the raw protobuf no longer contains attackScalars, or the decoding process has a bug?
```
    "templateId": "POKEMON_TYPE_BUG",
    "data": {
      "templateId": "POKEMON_TYPE_BUG",
      "typeEffective": {
        "attackScalar": [1.0, 0.625, 0.625, 0.625, 1.0, 1.0, 1.0, 0.625, 0.625, 0.625, 1.0, 1.6, 1.0, 1.6, 1.0, 1.0, 1.6, 0.625],
        "attackType": "POKEMON_TYPE_BUG"
      }
    }
```

**Comment by Furtif** [comment]
Look in https://github.com/Furtif/POGOProtos/blob/master/base/v0.185.1_obf.proto

**Comment by Furtif** [comment]
Find https://github.com/Furtif/POGOProtos/blob/master/compile_base.py#L270

**Comment by Furtif** [comment]
Look issue also in protos repo missing some oneof xxxx

**Comment by jerryyhom** [comment]
I understand the basics of protobuf, but I have no experience with the decoders.  However, when I look at the latest protobuf version, specifically for pokemon type, I see a bunch of bytes with a string pattern similar to the un-obfuscated attackScalar, as in my previous comment.  The pattern below looks like 18 values - I am pretty confident that is the attackScalar array in the protobuf.  So the decoding to json is missing the attackScalar.  Can you fix it?
```
^PPOKEMON_TYPE_BUG^R`
^PPOKEMON_TYPE_BUGBL
H^@^@\200?^@^@ ?^@^@ ?^@^@ ?^@^@\200?^@^@\200?^@^@\200?^@^@ ?^@^@ ?^@^@ ?^@^@\2\
00?\315\314\314?^@^@\200?\315\314\314?^@^@\200?^@^@\200?\315\314\314?^@^@ ?^P^G\
^Rv
```

**Comment by Furtif** [comment]
need decode bytes

**Comment by Furtif** [comment]
find a good proto edit decode bytes or replace bytes to good proto https://github.com/Furtif/POGOProtos/blob/master/compile_base.py#L270 and rebuild ..or if you uses other compile_base.py other and try again if not ok

**Comment by AlanStefann** [comment]
> should translate json always easier to translate repeated keys in json than translate protos all 💁🏻‍♂️🤷🏻‍♂️

Is there a way to automate the json translation from a kind of key ?
Or should I identify the 9 characters and replace the string by the non-obfuscated string, doing that from scratch at each new version ?

**Comment by Furtif** [comment]
some can be automated as I said in the open issue in the protos repo

**Comment by jerryyhom** [comment]
Looks like you fixed the attackScalar key.  Good job!

Your latest commit message says 99.9%, what else is missing?

**Comment by Furtif** [comment]
4 protos and one enum look base.proto end file and first enum

**Comment by Furtif** [comment]
if ok close this ! is deprecated now!
