### ISSUE TITLE
latest json doesn't exist 

### ISSUE THREAD

**Issue by westofer** [pokemongo-dev-contrib/pokemongo-game-master#124]
latest version doesn't work, since it doesn't have a `GAME_MASTER.json` in the repo

Here is my code
```
  let rawData = await gameMaster
    .getVersion("latest", "json")
    .then((rawData) => rawData.itemTemplate)
    .catch((error) => console.error(error));
```
I think I figured out where is the "bug" if it is one :)

in `node_modules/pokemongo-master-master/src/index.js` the following code
```
${FETCH_URL}/${version}/GAME_MASTER.${format}
```

I believe it should be

```
${FETCH_URL}/${version}/V2_GAME_MASTER.${format}
```
since "https://raw.githubusercontent.com/pokemongo-dev-contrib/pokemongo-game-master/master/versions/latest/GAME_MASTER.json" doesn't exist

Should I PR?

**Comment by Furtif** [comment]
https://github.com/pokemongo-dev-contrib/pokemongo-game-master/blob/master/src/index.js#L26 need be edited to v2_GAME_MASTER current uses old mode

**Comment by westofer** [comment]
should i change it? https://github.com/westofer/pokemongo-game-master/tree/patch-1

**Comment by westofer** [comment]
#125

**Comment by Furtif** [comment]
V2 is lower v2_XXXXX

**Comment by Furtif** [comment]
not is lower the bin json is Upper

**Comment by westofer** [comment]
great :)

**Comment by Furtif** [comment]
Parts of https://github.com/pokemongo-dev-contrib/pokemongo-game-master/issues/126
