### ISSUE TITLE
special moves mistakenly applied to all members of evolution line

### ISSUE THREAD

**Issue by dominicbarnes** [pokemongo-dev-contrib/pokemongo-game-master#26]
I recently started incorporating `special/` into my own application. I discovered that special moves (eg: "Draco Meteor") were applied to all members of the evolutionary line (ie: "Dratini", "Dragonair", "Dragonite") when it should only apply to the final stage (ie: "Dragonite"). In most cases, the special move only applies to the final evolution stage, not to the previous ones, with the main exception being "Last Resort" for all the Eeveelutions.

Is there a reason for this? Would it be reasonable to open a PR to correct this?

**Comment by celandro** [comment]
Please do. Need Metagross too
