### ISSUE TITLE
Cranidos and Rampardos Types

### ISSUE THREAD

**Issue by Drexlin** [pokemongo-dev-contrib/pokemongo-game-master#31]
Both pokemon have dual Rock types.

`    "templateId": "V0408_POKEMON_CRANIDOS",
    "pokemonSettings": {
      "pokemonId": "CRANIDOS",
      "modelScale": 1.26,
      "type": "POKEMON_TYPE_ROCK",
      "type2": "POKEMON_TYPE_ROCK",`

`    "templateId": "V0409_POKEMON_RAMPARDOS",
    "pokemonSettings": {
      "pokemonId": "RAMPARDOS",
      "modelScale": 1.26,
      "type": "POKEMON_TYPE_ROCK",
      "type2": "POKEMON_TYPE_ROCK",`

**Comment by Drexlin** [comment]
@BrunnerLivio Is this an issue with the raw GAME_MASTER file or this repo? Thanks.

**Comment by celandro** [comment]
This file is auto generated from the game master. It is not a bug.

Bugs are typically enum numbers showing up where strings should be.

**Comment by Drexlin** [comment]
That's what I was asking. Whether the issue is in the raw GM file or was it a bug in the way this repo processes it. I guess we can close this then. Thanks.
