### ISSUE TITLE
Do not use systemPath for dependency management

### ISSUE THREAD

**Issue by henrykuijpers** [pokemongo-dev-contrib/pokemongo-game-master#50]
pom.xml contains, since today, a reference to a dependency that is included in this repo. The reference is done using the systemPath option. This is considered bad practice. 

There should be a possibility to reference that jar through a normal maven dependency declaration.

**Comment by Furtif** [comment]
yes it get a warn but fine

**Comment by Furtif** [comment]
dependence  can't not exist in maven is local
best regards

**Comment by celandro** [comment]
Going to have to close this. 

Unfortunately for legal reasons the actual contributor of the decompiled protos wishes to be anonymous. I can only provide compiled binaries going forward. If Niantic ever contacts me saying this is not ok, this will also go away.

**Comment by Furtif** [comment]
@henrykuijpers there are no 50 solutions if you need protos and it is not published anymore I don't see that you can do better, in any case this repo is public if you have better ideas you can propose
