### ISSUE TITLE
Missing SKULL_BASH for cinematicMoves on SMEARGLE_MOVES_SETTING template

### ISSUE THREAD

**Issue by vnguyen972** [pokemongo-dev-contrib/pokemongo-game-master#60]
I can't find anywhere any issue on this but that is what I observed... Any idea? was it also missing from the protobuff Master file?

EDIT: Actually, there are quite a few with the same issue. These cinematic moves are not listed in SMEARGLE_MOVES_SETTINGS template.

SKULL_BASH
ACID_SPRAY
EARTH_POWER
POWER_UP_PUNCH
BLAZE_KICK
MUDDY_WATER
WEATHER_BALL_ROCK
WEATHER_BALL_WATER 
WEATHER_BALL_ICE 
WEATHER_BALL_FIRE

**Comment by Furtif** [comment]
fixed i thinks

**Comment by sarctechie** [comment]
As far as I remember, Smeargle cannot learn the moves released ever since it made its debut. That is on Ninatic's part.

**Comment by Furtif** [comment]
https://github.com/pokemongo-dev-contrib/pokemongo-game-master/blob/master/versions/latest/GAME_MASTER.json line 31644
