### ISSUE TITLE
Darumaka Evolution Branch

### ISSUE THREAD

**Issue by Drexlin** [pokemongo-dev-contrib/pokemongo-game-master#69]
Darumaka evolution branch isn't correctly formatted. There appears to be an extra set of brackets `}, {`. I believe this is the first pokemon that can evolve into 2 different "forms" (as opposed to 2 different pokemon).

So, this:
```
     "evolutionBranch": [{
        "evolution": "DARMANITAN",
        "candyCost": 50,
        "form": "DARMANITAN_STANDARD"
      }, {
        "evolution": "DARMANITAN",
        "form": "DARMANITAN_ZEN"
      }, {
        "candyCost": 50
      }],
```

Should be this:
```
     "evolutionBranch": [{
        "evolution": "DARMANITAN",
        "candyCost": 50,
        "form": "DARMANITAN_STANDARD"
      }, {
        "evolution": "DARMANITAN",
        "form": "DARMANITAN_ZEN"
        "candyCost": 50
      }],
```

Also, Darmanitan contains an evolution branch entry and shouldn't (it doesn't evolve).
```
      "evolutionBranch": [{
        "candyCost": 50
      }],
```

When I fixed those two issues manually, my parser was able to run successfully.

**Comment by jerryyhom** [comment]
The formatting issue is probably from Niantic, not the decoder, though that is just my guess.  Anyhow, my actual comment is to add more validation into your parser - that was my solution.  Manually correcting formatting issues is too burdensome.  When Niantic fixes the format, everyone will get the fix.

**Comment by Drexlin** [comment]
Thanks for the feedback!

I agree, it's probably an issue on Niantic's end, but I thought I'd write
the bug since this is the first occurrence of a Pokemon that can evolve
into two different forms. I'm not that familiar with the code, so I'll
leave that to the experts!

**Comment by jerryyhom** [comment]
Eh, is Cherubi in the same situation?  Nevertheless, I highly doubt the decoder cares whether a pokemon evolves into 0, 1, or n forms.

**Comment by Furtif** [comment]
https://github.com/pokemongo-dev-contrib/pokemongo-game-master/blob/master/versions/latest/GAME_MASTER.json line 161582
